# アプリケーション名
spring.application.name=my_portal

# JDBC設定
spring.datasource.url=jdbc:mysql://localhost:3306/my_portal
spring.datasource.username=harusame_user
spring.datasource.password=aIzawaEma@0131
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# セッションタイムアウト
server.servlet.session.timeout=30m

# MyBatisの設定
# Mapper XMLの配置場所（resources/mapper 配下に置く場合）
mybatis.mapper-locations=classpath:mapper/*.xml

# エンティティクラスのパッケージ（POJOを置いた場所）
mybatis.type-aliases-package=com.expeses.springboot.entity

# スネークケース → キャメルケース変換を有効化
mybatis.configuration.map-underscore-to-camel-case=true

# ログ出力（SQL確認用）
mybatis.configuration.log-impl=org.apache.ibatis.logging.slf4j.Slf4jImpl
